---

- name: Configure package
  become: True
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: systemd.service.j2
      dest: /etc/systemd/system/certbot.service
      mode: "0420"
    - src: systemd.timer.j2
      dest: /etc/systemd/system/certbot.timer
      mode: "0420"
    - src: cert-assembler.sh.j2
      dest: /etc/certbot/cert-assembler.sh
      mode: "0744"
  notify: Reload systemd

- name: Configure ETH
  include_tasks: dns-provider.yml
  vars:
    certbot_package: python3-certbot-dns-eth
    certbot_config: eth.ini
    certbot_domains: "{{ certbot_eth_domains }}"
    certbot_flags: >
      -a certbot-dns-eth-api:dns-eth-api
      --certbot-dns-eth-api:dns-eth-api-credentials
      /etc/certbot/eth.ini
      --certbot-dns-eth-api:dns-eth-api-propagation-seconds
      30
  when: certbot_eth_domains != []

- name: Configure Gandi
  include_tasks: dns-provider.yml
  vars:
    certbot_package: python3-certbot-gandi
    certbot_config: gandi.ini
    certbot_domains: "{{ certbot_gandi_domains }}"
    certbot_flags: >
      -a certbot-plugin-gandi:dns
      --certbot-plugin-gandi:dns-credentials /etc/certbot/gandi.ini
  when: certbot_gandi_domains != []

- name: Flush handlers
  meta: flush_handlers

- name: Start certbot
  become: True
  service:
    name: certbot.service
    state: started

- name: Enable automatic renewal
  become: True
  service:
    name: certbot.timer
    state: started
    enabled: True
