---

- name: Install package
  become: True
  apt:
    name: ['python3-protobuf', 'python3-certbot-dns-eth']
    state: present
    default_release: stretch-backports

- name: Configure package
  become: True
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: certbot-eth.ini.j2
      dest: /etc/letsencrypt/eth-dns.ini
      mode: "0600"
    - src: systemd.service.j2
      dest: /etc/systemd/system/certbot.service
      mode: "0420"
    - src: systemd.timer.j2
      dest: /etc/systemd/system/certbot.timer
      mode: "0420"
    - src: cert-assembler.sh.j2
      dest: /etc/certbot/cert-assembler.sh
      mode: "0744"
  notify: Reload systemd

- name: Request certificates
  become: True
  command: >
    certbot certonly
    -a certbot-dns-eth-api:dns-eth-api
    --certbot-dns-eth-api:dns-eth-api-credentials
    /etc/letsencrypt/eth-dns.ini
    --certbot-dns-eth-api:dns-eth-api-propagation-seconds
    30
    --test-cert
    -m {{ certbot_eth_email }}
    --agree-tos
    --keep
    {% for domain in item.domains %}
    -d '{{ domain }}'
    {% endfor %}
  with_items: "{{ certbot_eth_domains }}"

- name: Run cert-assembler
  become: True
  service:
    name: certbot.service
    state: started

- name: Enable automatic renewal
  become: True
  service:
    name: certbot.timer
    state: started
    enabled: True
